version: '3.8'

services:
  backend:
    build: .
    container_name: backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: python3 manage.py runserver 0.0.0.0:8000


  # Load testing services 
  # master:
  #   image: locustio/locust
  #   ports:
  #     - "8089:8089"
  #   volumes:
  #     - ./locust:/mnt/locust
  #   command: locust -f /mnt/locust/locust_file.py --master -user LocustUser

  # worker:
  #   image: locustio/locust
  #   volumes:
  #     - ./locust:/mnt/locust
  #   command: locust -f /mnt/locust/locust_file.py --worker --master-host=master
