version: '3.8'

services:
  backend:
    build: .
    container_name: django
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: gunicorn --bind 0.0.0.0:8000 --workers 4 root.wsgi


  redis:
    image: redis:latest
    restart: unless-stop
    ports:
      - "6379:6379"
    
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "8001:8001" 
    depends_on:
      - redis