# Generated by Django 4.2 on 2025-04-13 15:53

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.01'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.ForeignKey(default='P', on_delete=django.db.models.deletion.CASCADE, to='payments.paymentmodel'),
        ),
    ]
