# Generated by Django 4.2 on 2025-03-27 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='fashion', on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
    ]
